In [20]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [21]:
url ='https://en.wikipedia.org/wiki/World_energy_supply_and_consumption'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

In [83]:
#creating a dataframe with the websites table but excluding the foot of the table 
table_index = 0  
table = soup.find_all('table')[table_index]
df_from_website = pd.read_html(str(table))[0]
df_from_website = df_from_website.iloc[:-1]
new_df = pd.DataFrame(columns=df_from_website.columns)
for index, row in df_from_website.iterrows():
    new_df.loc[index] = row
    
new_df

              Unnamed: 0 Total (MToe) Coal Oil & Gas Renewable Nuclear
0                  China         2950  71%       13%       10%      6%
1          United States         2210  13%       69%        8%     10%
2                 Russia         1516  16%       78%        2%      4%
3           Saudi Arabia          610    0      100%         0       0
4                   Iran          354    0       99%         0      1%
5   United Arab Emirates          218    0       99%         0      1%
6                  India          615  50%       11%       33%      6%
7                 Canada          536   5%       81%       10%      4%
8              Indonesia          451  69%       17%       14%       0
9              Australia          423  64%       33%        3%       0
10                Brazil          325   1%       55%       42%      2%
11               Nigeria          249    0       47%       53%       0
12               Algeria          150    0      100%         0       0
13          South Africa          151  91%        1%        8%       0
14                Norway          214    0       93%        7%       0
15                France          128    0        1%       34%     65%
16               Germany          102  27%        3%       47%     23%

In [88]:
#creating a csv file 
#file_path = "output.csv"
#new_df.to_csv(file_path,index=False)